name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a new branch
        run: git checkout -b release-${{ github.run_number }}

      - name: Copy HTML and assets to release directory
        run: |
          mkdir -p release
          cp -r ./* release/

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update release"
          git push origin release-${{ github.run_number }}
