name: Release

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Your build process here, which might involve compiling assets and copying HTML files to a release directory.

      - name: Create release directory
        run: mkdir release
      
      - name: Copy HTML and assets to release directory
        run: cp -r assets/* release/

      - name: Create ZIP file
        run: zip -r release.zip ./release/*

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.repository.releases_url }}
          asset_path: ./release.zip
          asset_name: release-${{ github.sha }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
