name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install  # Replace with your build commands if necessary

      - name: Build
        run: npm run build  # Replace with your build commands if necessary

      - name: Create ZIP file
        run: zip -r release.zip ./*  # Adjust the file name and path as needed

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.repository.releases_url }}
          asset_path: ./release.zip  # Adjust the file name and path as needed
          asset_name: release.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
